server:
  port: ${SERVER_PORT}

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json
    min-response-size: 1024

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    cache:
      type: redis
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  application:
    name: ${APPLICATION_NAME}

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

rate-limit:
  api-url: ${API_URL}
  allowed-requests-per-second: ${ALLOWED_REQUESTS_PER_SECOND}