server:
  port: ${SERVER_PORT:8083}

  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,application/json
    min-response-size: 1024

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  datasource:
    cache:
      type: redis
    redis:
      host: localhost
      port: 6379

  application:
    name: ${APPLICATION_NAME:api}

  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
