version: "3.4"

services:
  gateway-1:
    image: pmatuan/distributed-rate-limit-demo:1.0
    container_name: gateway-1
    command:
      - "java"
      - "-jar"
      - "gateway.jar"

    ports:
      - "8080:8080"
    environment:
      - ACTIVE_PROFILE=docker
      - SERVER_PORT=8080
      - APPLICATION_NAME=gateway-1
      - API_URL=http://api:8083
      - ALLOWED_REQUESTS_PER_SECOND=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - my-network

  gateway-2:
    image: pmatuan/distributed-rate-limit-demo:1.0
    container_name: gateway-2
    command:
      - "java"
      - "-jar"
      - "gateway.jar"
    ports:
      - "8081:8081"
    environment:
      - ACTIVE_PROFILE=docker
      - SERVER_PORT=8081
      - APPLICATION_NAME=gateway-2
      - API_URL=http://api:8083
      - ALLOWED_REQUESTS_PER_SECOND=2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - my-network

  api:
    image: pmatuan/distributed-rate-limit-demo:1.0
    container_name: api
    command:
      - "java"
      - "-jar"
      - "api.jar"
    ports:
      - "8083:8083"
    environment:
      - ACTIVE_PROFILE=docker
      - SERVER_PORT=8083
      - APPLICATION_NAME=api
    networks:
      - my-network

  redis:
    image: redis:7.2.2
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
  default:
    driver: bridge
